const { Example } = require('cohere').classify;

const examples = [
  new Example(
    "Pedestrian Safety at Risk: Increase in Robberies Along Popular Walking Routes",
    "Toxic"),
  new Example(
    "Walkers Beware: Recent Spate of Hit-and-Runs Leaves Pedestrians Vulnerable",
    "Toxic"),
  new Example(
    "Danger Lurks for Pedestrians as Muggings and Assaults on Walking Routes Surge",
    "Toxic"),
  new Example("Pedestrian Routes Targeted by Thieves Stealing Personal Property",
          "Toxic"),
  new Example(
    "Pedestrian Fatalities Rise: Authorities Urge Caution on Dangerous Walking Routes",
    "Toxic"),
  new Example(
    "Violent Crimes Against Pedestrians on the Rise Along Certain Routes",
    "Toxic"),
  new Example(
    "Police Investigate Reports of Aggressive and Dangerous Behavior on Walking Routes",
    "Toxic"),
  new Example(
    "Pedestrian Safety Threatened by Increase in Vehicle Collisions on Busy Walking Routes",
    "Toxic"),
  new Example(
    "Residents Concerned Over Recent String of Pedestrian-Related Crimes on Popular Routes",
    "Toxic"),
  new Example(
    "Walkers Warned of Rising Danger on Streets and Walking Paths: Take Precautions.",
    "Toxic"),
  new Example("Local Business Wins Award for Sustainable Practices", "Benign"),
  new Example("Community Comes Together to Support Local Food Bank", "Benign"),
  new Example("New Park Opens to Public, Featuring Family-Friendly Attractions",
          "Benign"),
  new Example("Local High School Students Recognized for Achievements in Science",
          "Benign"),
  new Example(
    "City Implements New Recycling Program to Promote Environmental Sustainability",
    "Benign"),
  new Example("Historic Landmark Restored to Its Former Glory, Open for Visitors",
          "Benign"),
  new Example("Local Theater Group to Stage Shakespearean Classic", "Benign"),
  new Example("Annual Art Festival Draws Record Crowds to Downtown", "Benign"),
  new Example("City Council Approves Funding for New Community Center", "Benign"),
  new Example("Assault", "Toxic"),
  new Example("Arrest", "Toxic"),
  new Example("Killed", "Toxic"),
  new Example("Murder", "Toxic"),
  new Example("Death", "Toxic"),
  new Example("Stabbing", "Toxic"),
  new Example("Crime rate", "Toxic"),
  new Example("Burglary", "Toxic"),
  new Example("Robbery", "Toxic"),
  new Example("Homicide", "Toxic"),
  new Example("Theft", "Toxic"),
  new Example("Violence", "Toxic"),
  new Example("Crime", "Toxic"),
  new Example("Arson", "Toxic"),
  new Example("Domestic violence", "Toxic"),
  new Example("Sexual assault", "Toxic"),
  new Example("Hate crimes", "Toxic"),
  new Example("Kidnapping", "Toxic"),
  new Example("Gang violence", "Toxic"),
  new Example("Repeat offender", "Toxic"),
  new Example("offender", "Toxic"),
  new Example("No pedestrian crossings", "Toxic"),
  new Example("Poorly maintained sidewalks", "Toxic"),
  new Example("Unmarked crosswalks", "Toxic"),
  new Example("Absence of pedestrian safety measures", "Toxic"),
  new Example("Poorly lit areass", "Toxic"),
  new Example("Intoxicated drivers", "Toxic"),
  new Example("Homeless encampments", "Toxic"),
  new Example("Panhandling", "Toxic"),
  new Example("Aggressive behavior by homeless people", "Toxic"),
  new Example("Public defecation or urination", "Toxic"),
  new Example("Increased crime rates in areas with homeless populations", "Toxic"),
  new Example("Harassment of pedestrians by homeless individuals", "Toxic"),
  new Example("Encampment fires or other hazards", "Toxic"),
  new Example("Aggressive behavior by homeless people", "Toxic"),
  new Example("Used drug paraphernalia on sidewalks", "Toxic"),
  new Example("Sleeping or camping in doorways", "Toxic"),
  new Example("Aggressive begging", "Toxic"),
  new Example("Human waste and trash in public spaces", "Toxic"),
  new Example("Human trafficking", "Toxic"),
  new Example("Restaurant", "Benign"),
  new Example("Family", "Benign"),
  new Example("Charity", "Benign"),
]